from __ import __
import random
text=['hello','world','I','love','you']
__()
random.seed(48950)
num=random.randint(1,100)
print(num)
num=random.random()
print(num)
num=random.uniform(100,10)
print(num)
__()
num=random.choice(text)
print(num)
num=random.randrange(1,100,5)
print(num)
num=random.sample(text,3)
print(num)
random.shuffle(text)
print(text)
__()
